services:

  server:
    build: ./backend
    container_name: vitalink-server
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: unless-stopped

  client:
    build: ./frontend
    container_name: vitalink-client
    ports:
      - "5173:5173"
    depends_on:
      - server
    restart: unless-stopped
